# Spring properties
spring:
  application:
    name: auth-service

  # Neo4j properties
  data:
    neo4j:
      username: neo4j
      password: secret
      uri: bolt://localhost:7687

# HTTP Server
server:
  port: 8080

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# App JWT Properties
jwt:
  secret: auth-service-secret
  expiration: 172800 #seconds
